---
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack providing cross account access for CloudSploit
# Name : cloudsploit-organizations-role

Parameters:

  CloudSploitCentralAccount:
    Description: AWS account ID where CloudSploit is installed
    Type: String
    ConstraintDescription: Must be a valid AWS account ID

  CloudSploitOrgRoleExternalId:
    Description: CloudSploit Role ExternalID
    Type: String

  CloudSploitStackSetSpokeName:
    Description: Name of the StackSet in charge of distributing spoke account assets
    Type: String
    Default: cloudsploit-spoke-account

Resources:

  CloudSploitOrgRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloudsploit-organizations-role
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${CloudSploitCentralAccount}:root'
          Action:
          - sts:AssumeRole
          Condition:
            StringEquals:
              "sts:ExternalId": !Sub '${CloudSploitOrgRoleExternalId}'
      Policies:
      - PolicyName: "AllowOrganizationListAccounts"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: organizations:ListAccounts
            Resource: '*'
      - PolicyName: "AllowUpdateStackInstances"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - cloudformation:CreateStackInstances
            - cloudformation:ListStackInstances
            Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stackset/${CloudSploitStackSetSpokeName}:*"
