---
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack providing cross account access for CloudSploit
# Name : cloudsploit-spoke-account

Parameters:

  CloudSploitCentralAccount:
    Description: AWS account ID where CloudSploit is installed
    Type: String
    ConstraintDescription: Must be a valid AWS account ID

  CloudSploitRoleExternalId:
    Description: CloudSploit Role ExternalID
    Type: String

Resources:

  CloudSploitScanAssumeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloudsploit-scan-role
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${CloudSploitCentralAccount}:root'
          Action:
          - sts:AssumeRole
          Condition:
            StringEquals:
              "sts:ExternalId": !Sub '${CloudSploitRoleExternalId}'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
      Path: "/"
