AWSTemplateFormatVersion: '2010-09-09'
Description: Common resources for CloudSploit Batch
# Stack Name : cloudsploit-common
# Description : this stack creates the CloudSploit main stack prerequisites :
# - one ECR repository
# - if needed, one S3 bucket to store reports (otherwise use an external one)

Parameters:

  TagBlock:
    Description: Applicative block tag
    Type: String
    Default: security

  TagApp:
    Description: Application tag
    Type: String
    Default: cloudsploit

  TagOrg:
    Description: Organization tag
    Type: String
    Default: cloudteam

  CloudSploitEcrRepoName:
    Description: ECR name for the CloudSploit repo
    Type: String
    Default: cloudsploit

  UseOwnReportingBucket:
    Description: Enable a dedicated Bucket to store reports
    Type: String
    Default: true
    AllowedValues: [true, false]

Conditions:
  HasOwnReportingBucket: !Equals [!Ref UseOwnReportingBucket, true]

Resources:

  CloudSploitEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref CloudSploitEcrRepoName
      Tags:
      - Key: Block
        Value: !Ref TagBlock
      - Key: App
        Value: !Ref TagApp
      - Key: Org
        Value: !Ref TagOrg

  CloudSploitReportingBucket:
    Type: AWS::S3::Bucket
    Condition: HasOwnReportingBucket
    Properties:
      BucketName: !Sub '${TagApp}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      Tags:
      - Key: Block
        Value: !Ref TagBlock
      - Key: App
        Value: !Ref TagApp
      - Key: Org
        Value: !Ref TagOrg

Outputs:

  CloudSploitEcrRepository:
    Description: CloudSploit ECR repository Arn
    Value: !GetAtt CloudSploitEcrRepository.Arn
    Export:
      Name: !Sub "${AWS::StackName}-EcrRepository"
